"""
Streams an agent's final natural-language turn token-by-token, skipping
intermediate tool-call turns (which have no user-visible content — a real
tool call and the eventual final answer both arrive as
`on_chat_model_stream` events, but a tool-call chunk has empty `content`
and populated `tool_call_chunks`, while the final answer's chunks have
real `content` and empty `tool_call_chunks`). Verified live with a
scripted fake model driving a real tool call before the final answer.

recursion_limit is explicit and low on purpose: caught live, a model
given an under-specified query (a tool needing an ID it wasn't given)
looped for the full default 25 steps — 38+ seconds — before LangGraph's
own limit finally killed it. None of our agents legitimately need more
than a couple of tool-call round trips, so a stuck agent should fail in
a couple seconds, not 38.
"""

from typing import AsyncIterator

from observability import trace_config

RECURSION_LIMIT = 10


async def stream_agent_answer(agent, query: str) -> AsyncIterator[str]:
    """Yields token strings as they're generated by the agent's final
    turn. Caller is responsible for accumulating them if it needs the
    full text afterward (e.g. for caching or the confidence check)."""
    async for event in agent.astream_events(
        {"messages": [{"role": "user", "content": query}]},
        version="v2",
        config=trace_config({"recursion_limit": RECURSION_LIMIT}),
    ):
        if event["event"] != "on_chat_model_stream":
            continue
        chunk = event["data"]["chunk"]
        if chunk.content and not chunk.tool_call_chunks:
            yield chunk.content
